name: Get Secret
on:
  workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        env:
          MY_SECRET: ${{ secrets.OPENWA_API_KEY }}
        run: |
          echo "$MY_SECRET" | base64
